### ISSUE TITLE
Error: Cannot find module 'forthnode.js'

### ISSUE THREAD

**Issue by vechnoe** [yarus23/SPF.JS#6]
Hi,  I run the console and get the error that this module does not exist. (No module file): 

`maximus@maximus:~/SPF.JS$ node forthnode.js

module.js:340
    throw err;
          ^
Error: Cannot find module '/home/maximus/SPF.JS/forthnode.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
`

How to fix this bug?

Best regards,
Maxim Chernyatevich

**Comment by yarus23** [comment]
What version of node.js do you use?

**Comment by yarus23** [comment]
Try node forthnode_cli.js

**Comment by vechnoe** [comment]
> what version of node.js do you use?

I use node v0.10.29, debian 8

**Comment by vechnoe** [comment]
> Try node forthnode_cli.js

The same error: `Cannot find module './forthnode.js'`

**Comment by yarus23** [comment]
I have forgotten to add tihs file to repository, please update and try again.

**Comment by vechnoe** [comment]
Thank you. It works ok with node 6.x
